### ISSUE TITLE
Wording issues in Client-Server Lesson

### ISSUE THREAD

**Issue by anonymous2020andbeyond** [learn-co-curriculum/dsc-the-client-server-model#2]
## Link to Canvas

https://learning.flatironschool.com/courses/6221/pages/the-client-server-model?module_item_id=529097

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x ] Instructions unclear
- [ ] Other (explain below)

### Source

```
1.  Web Server Paragraph: "A web server in a Web application is what listens to requests coming in from the clients. When you set up an HTTP (HyperText Transfer Protocol - Language of the internet) server, we set it up to listen to a port number. A port number is always associated with the IP address of a computer. You can think of ports as separate channels on a computer that we can use to perform different tasks: one port could be surfing [www.facebook.comLinks to an external site.](http://www.facebook.com/) while another fetches your email. This is possible because each of the applications (the Web browser and the email client) use different port numbers.

Once you've set up an HTTP server to listen to a specific port, the server waits for client requests coming to that specific port.."
```

### Concern

1. The switch between "you" and "we" is a bit confusing.  Also, not clear if the server is listening to a port on the user's client computer or if the server is listening to a port on the server.

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by christine-egan42** [comment]
Corrected in GitHub repo and merged changes.
